#tomcat port
server:
  port: 8094

spring:
  profiles.active: local
  # ??? ?? ??
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/music?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345
  # JPA ??
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true
  # Security OAuth
  security:
    oauth2.client:
      registration:
        google:
          clientId: "433034212344-jl87b2ah39o9ep5ap1krkmq095o9tqh1.apps.googleusercontent.com"
          clientSecret: "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"
          scope:
            - email
            - profile
        facebook:
          clientId: "844389587101823"
          clientSecret: "074c9d27b7b87c5094208bd7a4bd0359"
          scope:
            - email
            - public_profile
        naver:
          clientId: "RuFDtPwREu_sy9hg6vPv"
          clientSecret: "bVJcnE_F7b"
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "http://localhost:8094/login/oauth2/code/naver"
          scope:
            - name
            - nickname
            - email
            - profile_image
          clientName: Naver
        kakao:
          clientId: "{??? client-id}"
          clientSecret: "{??? client-secret}"
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          scope:
            - profile_nickname
            - profile_image
            - account_email
          clientName: Kakao
      # Provider ??
      provider:
        naver:
          authorizationUri: https://nid.naver.com/oauth2.0/authorize
          tokenUri: https://nid.naver.com/oauth2.0/token
          userInfoUri: https://openapi.naver.com/v1/nid/me
          userNameAttribute: response
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttribute: id
  # REST API
  data:
    rest:
      basePath: /api
      default-page-size: 10

# cors ??

# jwt secret key ??
jwt.secret: "8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds"

# ?? ?? secret Key ? RedirectUri ??
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect
